apiVersion: apps/v1
kind: Deployment
metadata:
  name: minisocial-fronend-deployment-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minisocial-fronend-v2
  template:
    metadata:
      labels:
        app: minisocial-fronend-v2
    spec:
      containers:
      - name: minisocial-fronend-v2
        image: ganeshchile0307/minisocialapp-frontend:1.0
        ports:
          - containerPort: 80
        

---
apiVersion: v1
kind: Service
metadata:
  name: minisocial-fronend-service-v2
  labels:
    app: minisocial-fronend-v2
spec:
  selector:
    app: minisocial-fronend-v2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31001
  type: NodePort